/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FileManagerImport } from './routes/file-manager'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FileManagerRoute = FileManagerImport.update({
  id: '/file-manager',
  path: '/file-manager',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/file-manager': {
      id: '/file-manager'
      path: '/file-manager'
      fullPath: '/file-manager'
      preLoaderRoute: typeof FileManagerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/file-manager': typeof FileManagerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/file-manager': typeof FileManagerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/file-manager': typeof FileManagerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/file-manager'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/file-manager'
  id: '__root__' | '/' | '/file-manager'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FileManagerRoute: typeof FileManagerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FileManagerRoute: FileManagerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/file-manager"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/file-manager": {
      "filePath": "file-manager.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
